version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react-portfolio
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: deploy/BeforeInstall.sh
      runas: ubuntu
  AfterInstall:
    - location: deploy/AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: deploy/ApplicationStart.sh
      runas: ubuntu